Appveyor: Fix error:
:: msys2-runtime and catgets are in conflict. Remove catgets? [y/N] error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: msys2-runtime and catgets are in conflict