Update to rcd-1.12.0
Error for missing include was:

```
In file included from ViewStyle.cxx:17:
./SplitVector.h:181:9: error: no member named 'fill' in namespace 'std'
  181 |                         std::fill(&body[part1Length], &body[part1Length + insertLength], v);
      |                              ^~~~
```